Testimoni/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *

urlpatterns = [
   path('', indexs, name='testimoni'),
   url(r'^testimoni/', testimoni, name= 'testimonii')
]

berikan/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, include, path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^auth/', include('social_django.urls', namespace='social_auth')),
    re_path(r'^', include('landing_page.urls', namespace='landing-page')),
    re_path(r'^', include('registrasi.urls', namespace='registrasi')),
    re_path(r'^', include('donasi.urls', namespace='donasi')),
    re_path(r'^', include('berita.urls', namespace='berita')),
    path('testimoni/',include(('Testimoni.urls','Testimoni'),namespace='Testimoni')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

berita/urls.py
from django.urls import re_path
from berita.views import daftar_berita, daftar_program_donasi_dari_berita

app_name = 'berita'

urlpatterns = [
    re_path(r'^berita/$', daftar_berita, name='daftar-berita'),
    re_path(r'^berita/(?P<pk>[0-9]+)/daftar-program-donasi/$', daftar_program_donasi_dari_berita, name='daftar-program-donasi-dari-berita'),
]

donasi/urls.py
from django.urls import re_path
from donasi.views import daftar_program_donasi, detail_program_donasi, daftar_donatur_program_donasi

app_name = 'donasi'

urlpatterns = [
    re_path(r'^program-donasi/$', daftar_program_donasi, name='daftar-program-donasi'),
    re_path(r'^program-donasi/(?P<pk>[0-9]+)/$', detail_program_donasi, name='detail-program-donasi'),
    re_path(r'^program-donasi/(?P<pk>[0-9]+)/donatur$', daftar_donatur_program_donasi, name='daftar-donatur-program-donasi'),
]

landing_page/urls.py
from django.urls import re_path
from .views import landing_page

app_name = 'landing_page'

urlpatterns = [
    re_path(r'^$', landing_page, name='landing-page')
]

registrasi/urls.py
from django.urls import re_path
from .views import registrasi, login_view, logout_view

app_name = 'registrasi'

urlpatterns = [
	re_path(r'^registrasi$', registrasi, name = 'registrasi'),
	re_path(r'^login$', login_view, name = 'login'),
	re_path(r'^logout$', logout_view, name = 'logout'),
]

common_files/templates/base.html
{% load static %}

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Berikan</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'styles/bootstrap-ns.min.css' %}">
	    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
        {% block additional_styles %}
        {% endblock %}
    </head>
    <body>
        {% include "header.html" %}
        {% block content %}
        {% endblock %}
        {% include "footer.html" %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>

        {% block additional_scripts %}
        {% endblock %}
    </body>
</html>

common_files/templates/footer.html
<footer class="footer">
    <p>2018 &copy; di Berikan oleh SinarPerak</p>
</footer>

common_files/templates/forbidden.html
{% extends 'base.html' %}
{% load static %}

{% block additional_styles %}
	<link rel="stylesheet" href="{% static 'registrasi/styles/registrasi.css' %}">
{% endblock %}

{% block content %}
    <div class="twbs">
        <div class="container">
            <div class="row">
                <div class="jumbotron text-justify bg-dimgray">
                    <h1 class="text-palegreen">Forbidden 403!</h1>
                    <p class="lead text-white">
                        Anda dilarang untuk mengakses halaman ini!
                        Anda akan segera diarahkan ke landing page.
                        Silakan klik di <a class="text-palegreen" href="{% url 'landing-page:landing-page' %}">sini</a> jika browser Anda tidak mengarahkan Anda.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <script>
        function redirect(){
            window.location.href = "{% url 'landing-page:landing-page' %}";
        }
    
        setTimeout(redirect, 3000);
    </script>
{% endblock %}

common_files/templates/header.html
<nav class="navbar">
    <ul class="navbar-container">
        <a href="{% url 'landing-page:landing-page' %}"><img src="https://cdn.pbrd.co/images/HJiK7qC.png"></a>
        <div>
            <a class="navbar-link" href="{% url 'berita:daftar-berita' %}">Berita</a>
            <a class="navbar-link" href="{% url 'donasi:daftar-program-donasi' %}">Donasi</a>
            {% if not request.user.is_authenticated %}
            <a class="navbar-link" href="{% url 'registrasi:registrasi' %}">Daftar</a>
            <a class="navbar-link" href="{% url 'registrasi:login' %}">Login</a>
            {% else %}
            <span class="navbar-link">
                Welcome, {{ request.user.name }}
                {% if request.session.image_url %}
                <img src="{{ request.session.image_url }}" class="profile-image" alt="Responsive image">
                {% endif %}
            </span>
            <a class="navbar-link" href="{% url 'registrasi:logout' %}">Logout</a>
            {% endif %}
			<a class="navbar-link" href="{% url 'Testimoni:testimoni' %}">About Us</a>
        </div>
    </ul>
</nav>